### PR TITLE
Allow developer to get a court by its court code

### PR DESCRIPTION
**Pull request by plocket**
Test:
1. Run docassemble/MACourts/data/questions/test_get_court_by_code.yml.
1. Enter the court code of a court you're familiar with.
1. See the resulting name on the next page.

### CODE REVIEW

**Review by nonprofittechy — COMMENTED** [review]
Rather than [0] safer to use next(iter(...),None) here I think? Or maybe filter already handles that.

**Comment by plocket** [comment]
I don't know this thing of which you speak, but I will look it up.

**Comment by plocket** [comment]
Also, can't believe I didn't test the empty case. Sheesh.

**Comment by plocket** [comment]
There, that should have a more sensical and handleable failure case.

**Comment by nonprofittechy** [comment]
Great. I keep `next()` and `.get()` in my toolbox to deal with empty lists/other iterators. As nice as Python is, dealing with None requires defensive programming :)

**Comment by nonprofittechy** [comment]
Accepted with changes

**Pull request merged**
